FROM debian:bullseye

ENV TZ=America/New_York
ENV PATH=/go/bin:$PATH

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &&\
    apt update &&\
    apt -y install build-essential &&\
    apt -y install gdal-bin gdal-data libgdal-dev

WORKDIR /app
COPY main .
CMD ["./main"]